export const messagesToasts = {
    loginFail: 'Fail to login!',
    loginSuccess: 'Success to login!',
    passwordIncorrect: 'The password is incorrect!',
    registerFail: 'Fail to register!',
    registerHaveNotEnoughInfo: 'Please enter enough infomation!',
    registerSuccess: 'Success to register!',
    registerWarning: 'Email already exists!',
    updateSucess: 'Sucess to update!',
    updateFail: 'Fail to update!',
    updatePasswordSuccess: 'Sucess to update password!',
    updatePasswordFail: 'Fail to update password!',
    updatePasswordFailToIncorrect: 'Old password is incorrect!',
    createPostSuccess: 'Create post is success!',
    createPostFail: 'Create post is fail!',
    deleteSuccess: 'Delete is success!',
    deleteFail: 'Fail to delete!',
};
